package org.ecc.pmp.model;
// Generated Jan 3, 2018 1:14:58 AM by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name = "DEPT")
public class Dept implements java.io.Serializable {

	private BigDecimal deptno;
	private String dname;
	private String loc;
	private Set<Emp> emps = new HashSet<Emp>(0);

	public Dept() {
	}

	public Dept(BigDecimal deptno) {
		this.deptno = deptno;
	}

	public Dept(BigDecimal deptno, String dname, String loc, Set<Emp> emps) {
		this.deptno = deptno;
		this.dname = dname;
		this.loc = loc;
		this.emps = emps;
	}

	@Id

	@Column(name = "DEPTNO", unique = true, nullable = false)
	public BigDecimal getDeptno() {
		return this.deptno;
	}

	public void setDeptno(BigDecimal deptno) {
		this.deptno = deptno;
	}

	@Column(name = "DNAME", length = 4000)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@Column(name = "LOC", length = 4000)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	/*@OneToMany(fetch = FetchType.EAGER, mappedBy = "dept")
	public Set<Emp> getEmps() {
		return this.emps;
	}

	public void setEmps(Set<Emp> emps) {
		this.emps = emps;
	}
*/
}
