package org.ecc.pmp.model;
// Generated Nov 12, 2017 10:26:32 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name = "DEPT", schema = "MMISHRA")
public class Dept implements java.io.Serializable {

	private int deptno;
	private String dname;
	private String loc;

	public Dept() {
	}

	public Dept(int deptno) {
		this.deptno = deptno;
	}

	public Dept(int deptno, String dname, String loc) {
		this.deptno = deptno;
		this.dname = dname;
		this.loc = loc;
	}

	@Id

	@Column(name = "DEPTNO", unique = true, nullable = false, precision = 5, scale = 0)
	public int getDeptno() {
		return this.deptno;
	}

	public void setDeptno(int deptno) {
		this.deptno = deptno;
	}

	@Column(name = "DNAME", length = 224)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@Column(name = "LOC", length = 208)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

}
